[package]
name = "RandomColor"
version = "0.1.0"
authors = ["Lucas Maximiliano Marino <lucasmmarino@icloud.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/elementh/RandomColor.git"
homepage ="https://github.com/elementh/RandomColor"
description = ":gear: :art: Rust package for generating random attractive colors"

[dependencies]
rand = "0.3.15"
