[package]
name = "random_color"
version = "0.4.3"
authors = ["Lucas Maximiliano Marino <lucasmmarino@icloud.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/elementh/random_color.git"
homepage ="https://github.com/elementh/random_color"
description = "Rust crate for generating random attractive colors"

[dependencies]
rand = "0.3.15"
