[package]
name = "random_color"
version = "0.2.0"
authors = ["Lucas Maximiliano Marino <lucasmmarino@icloud.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/elementh/random_color.git"
homepage ="https://github.com/elementh/random_color"
description = ":gear: :art: Rust package for generating random attractive colors"

[dependencies]
rand = "0.3.15"
